import {
  addDays,
  todayISO,
  uid,
  type Attachment,
  type Workspace,
} from "./domain";

export function demoWorkspace(files: Attachment[]): Workspace {
  const accounts = [
    {
      id: uid(),
      network: "Instagram" as const,
      handle: "@studiolume",
      label: "Lume principal",
      kind: "Empresa" as const,
    },
    {
      id: uid(),
      network: "TikTok" as const,
      handle: "@studiolume",
      label: "TikTok principal",
      kind: "Empresa" as const,
    },
    {
      id: uid(),
      network: "LinkedIn" as const,
      handle: "studiolume",
      label: "Studio Lume",
      kind: "Empresa" as const,
    },
    {
      id: uid(),
      network: "TikTok" as const,
      handle: "@lumelab",
      label: "Lume Lab",
      kind: "Dark" as const,
    },
    {
      id: uid(),
      network: "TikTok" as const,
      handle: "@lume.cortes",
      label: "Cortes criativos",
      kind: "Dark" as const,
    },
  ];
  const today = todayISO(),
    now = new Date().toISOString();
  const entries = [
    {
      title: "Bastidores do studio",
      offset: 0,
      time: "12:00",
      account: 0,
      format: "Carrossel",
      status: "Publicado" as const,
      files: [files[0], files[3]],
    },
    {
      title: "O detalhe faz diferença",
      offset: 0,
      time: "18:30",
      account: 0,
      format: "Post",
      status: "Rascunho" as const,
      files: [files[3]],
    },
    {
      title: "Uma nova forma de criar",
      offset: 1,
      time: "09:00",
      account: 0,
      format: "Carrossel",
      status: "Planejado" as const,
      files: [files[1], files[3]],
    },
    {
      title: "Nosso processo criativo",
      offset: 1,
      time: "17:00",
      account: 2,
      format: "Post",
      status: "Planejado" as const,
      files: [files[2]],
    },
    {
      title: "Ideias para guardar",
      offset: 2,
      time: "10:00",
      account: 0,
      format: "Post",
      status: "Rascunho" as const,
      files: [files[1]],
    },
    {
      title: "Da ideia ao resultado",
      offset: 3,
      time: "19:00",
      account: 3,
      format: "Carrossel",
      status: "Planejado" as const,
      files: [files[0], files[2]],
    },
    {
      title: "Salve esta referência",
      offset: 4,
      time: "12:00",
      account: 0,
      format: "Carrossel",
      status: "Planejado" as const,
      files: [files[1], files[3]],
    },
    {
      title: "Uma pausa para inspirar",
      offset: 5,
      time: "11:00",
      account: 0,
      format: "Post",
      status: "Planejado" as const,
      files: [files[2]],
    },
  ];
  return {
    version: 1,
    profile: {
      userName: "Ana",
      companyName: "Studio Lume",
      timeZone: "America/Sao_Paulo",
      accounts,
    },
    posts: entries.map((e) => ({
      id: uid(),
      title: e.title,
      accountId: accounts[e.account].id,
      network: accounts[e.account].network,
      format: e.format,
      caption:
        "Um pouco do que acontece antes de tudo ganhar forma. Ideias, testes e os detalhes do nosso processo.\n\n#StudioLume #ProcessoCriativo",
      date: addDays(today, e.offset),
      time: e.time,
      reminderMinutes: 15,
      status: e.status,
      attachments: e.files.filter(Boolean),
      createdAt: now,
      updatedAt: now,
    })),
    trash: [],
  };
}
